spring.application.name=bc_maps_system
server.address=0.0.0.0
server.port=8080

logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO

spring.datasource.url=jdbc:h2:file:./data/bc_maps_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.upload.dir=uploads

spring.jpa.open-in-view=false
