spring.application.name=bc_maps_system
server.port=8080

logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO

spring.datasource.url=jdbc:h2:mem:bc_maps_db
#spring.datasource.url=jdbc:h2:file:./data/bc_maps_db // Juste pour une base de donnees persistante
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
